export enum Sector {
  TECHNOLOGY = 'Technology',
  INDUSTRIAL_GOODS_AND_SERVICES = 'Industrial Goods & Services',
  FOOD_BEVERAGE_AND_TOBACCO = 'Food, Beverage & Tobacco',
  TELECOMMUNICATIONS = 'Telecommunications',
  CONSTRUCTION_AND_MATERIALS = 'Construction & Materials',
  AUTOMOBILES_AND_PARTS = 'Automobiles & Parts',
  RETAIL = 'Retail',
  OIL_AND_GAS = 'Oil & Gas',
  BANKS = 'Banks',
  REAL_ESTATE = 'Real Estate',
  HEALTH_CARE = 'Health Care',
  PERSONAL_AND_HOUSEHOLD_GOODS = 'Personal & Household Goods',
  CONSUMER_PRODUCTS_AND_SERVICES = 'Consumer Products & Services',
  UTILITIES = 'Utilities',
  CHEMICALS = 'Chemicals',
  TRAVEL_AND_LEISURE = 'Travel & Leisure',
  MEDIA = 'Media',
  BASIC_RESOURCES = 'Basic Resources',
  INSURANCE = 'Insurance',
  FINANCIAL_SERVICES = 'Financial Services',
}
